### PR TITLE
Update tutor CMD nya

### PR DESCRIPTION
**Pull request by hdiiofficial**

### CODE REVIEW

**Comment by plexavor** [comment]
Coba jelasin kenapa harus python3?

**Comment by FatihArridho** [comment]
> Coba jelasin kenapa harus python3?

btul tuh

**Comment by hdiiofficial** [comment]
> Coba jelasin kenapa harus python3?

Error

**Comment by FatihArridho** [comment]
> > Coba jelasin kenapa harus python3?
> 
> Error

Pakai termux? Atau apa? Ss coba

**Comment by hdiiofficial** [comment]
> > > Coba jelasin kenapa ha
> 
> Pakai termux? Atau apa? Ss coba

Vps Ubuntu awokawok

**Comment by hdiiofficial** [comment]
Dh

**Comment by FatihArridho** [comment]
> > > > Coba jelasin kenapa ha
> > 
> > 
> > Pakai termux? Atau apa? Ss coba
> 
> Vps Ubuntu awokawok

Yaudah kalau vps Ubuntu pakai python3 aja

**Comment by hdiiofficial** [comment]
> > > > > Coba jelasin kenapa ha
> > > 
> > > 
> > > Pakai termux? Atau apa? Ss coba
> > 
> > 
> > Vps Ubuntu awokawok
> 
> Yaudah kalau vps Ubuntu pakai python3 aja

True min

**Pull request closed without merging**
